# Generated by Django 5.2 on 2025-04-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_out', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='action',
            field=models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out')], max_length=10),
        ),
    ]
